# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
                
        edit_article_view_thumbnail:
            filters:
                downscale:
                    max: [800, 600]
        
        users_avatar:
            quality: 85
            filters:
                scale:
                    dim: [ 250, 250 ]