security:

    encoders:
        App\Entity\User: 'bcrypt'

    enable_authenticator_manager: true

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: 'App\Entity\User'
                property: 'email'
    firewalls:
        dev:
            # Permet d'afficher la debug bar et de ne pas appliquer de sécurité, pareil pour les fichiers assets.
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login

            logout:
                path: app_logout
            
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine en seconde
                path: /

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
            custom_authenticators:
                - App\Security\LoginFormAuthenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/assembly, roles: ROLE_ASSEMBLY }
        - { path: ^/editor, roles: ROLE_EDITOR }
        - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_EDITOR: ROLE_USER
        ROLE_ASSEMBLY: ROLE_EDITOR
        ROLE_ADMIN: ROLE_ASSEMBLY