vich_uploader:
    db_driver: orm

    mappings:
        posts_image:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            # A activer si l'on veux supprimer l'image.
            # delete_on_update: true
            # delete_on_remove: true