vich_uploader:
    db_driver: orm

    mappings:
        posts_image:
            uri_prefix: /uploads/posts_image
            upload_destination: '%kernel.project_dir%/public/uploads/posts_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            # A activer si l'on veux supprimer l'image.
            delete_on_update: true
            delete_on_remove: true

        users_image:
            uri_prefix: /uploads/users_image
            upload_destination: '%kernel.project_dir%/public/uploads/users_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_remove: true # suppression du fichier à la suppression de l’entité
            delete_on_update: true # suppression du fichier quand un nouveau fichier est envoyé